name: Shell commands #Workflow

on: [push] #event-trigger

jobs:
  run-shell-command: #job name
    runs-on: ubuntu-latest #runner
    steps:
      - name: echo a string
        run: echo "Hello Github Workflows"
      - name: Multiline script
        run: |
          node -v
          npm -v

      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python