name: Shell commands #Workflow

on: [push] #event-trigger

jobs:
  run-shell-command: #job name
    runs-on: ubuntu-latest #runner
    steps:
      - name: Print working Directory
        run: pwd
      - name: echo a string
        run: echo "Hello Github Workflows"
      - name: Multiline script
        run: |
          node -v
          npm -v

      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command: 
    runs-on: windows-2019
    needs: [run-shell-command] #maked it dependant on the job "run-shell-command"
    steps:
      - name: Directory Powershell
        run: |
          get-location
          hostname
          Get-ComputerInfo
      - name: Directory Bash
        run: pwd
        shell: bash